// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3Emxj2SPSyFeDZL1uVU9FRw060Tch1uY',
    appId: '1:994540711682:web:21fb6a8e72ddec5ee8dc1b',
    messagingSenderId: '994540711682',
    projectId: 'student-record-tracker-b836b',
    authDomain: 'student-record-tracker-b836b.firebaseapp.com',
    storageBucket: 'student-record-tracker-b836b.firebasestorage.app',
    measurementId: 'G-BBXQ38MERZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy3y3Xe0GYpOAJ7uKmd5iwPxJOVhC3Igk',
    appId: '1:994540711682:android:02b8689ceae92e09e8dc1b',
    messagingSenderId: '994540711682',
    projectId: 'student-record-tracker-b836b',
    databaseURL: 'https://student-record-tracker-b836b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'student-record-tracker-b836b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYTGY9HOA9Wq280z_KNPZn80Z-Dettldw',
    appId: '1:994540711682:ios:5befee68780de528e8dc1b',
    messagingSenderId: '994540711682',
    projectId: 'student-record-tracker-b836b',
    storageBucket: 'student-record-tracker-b836b.firebasestorage.app',
    iosBundleId: 'com.example.studentRecordDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYTGY9HOA9Wq280z_KNPZn80Z-Dettldw',
    appId: '1:994540711682:ios:5befee68780de528e8dc1b',
    messagingSenderId: '994540711682',
    projectId: 'student-record-tracker-b836b',
    storageBucket: 'student-record-tracker-b836b.firebasestorage.app',
    iosBundleId: 'com.example.studentRecordDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3Emxj2SPSyFeDZL1uVU9FRw060Tch1uY',
    appId: '1:994540711682:web:2d6486b34e38e220e8dc1b',
    messagingSenderId: '994540711682',
    projectId: 'student-record-tracker-b836b',
    authDomain: 'student-record-tracker-b836b.firebaseapp.com',
    storageBucket: 'student-record-tracker-b836b.firebasestorage.app',
    measurementId: 'G-FLTHDFSWYE',
  );
}